<?xml version="1.0" ?>
<robot name="tether" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Xacro to generate tether SDF -->
    <!-- Note: need to manually find and replace all references to 'continuous'
    with 'ball' in final SDF to get better tether-->

    <!-- Define properties -->
    <xacro:property name="tether_length" value="1.5" />
    <xacro:property name="tether_radius" value="0.01" />
    <xacro:property name="tether_mass" value="0.1" />
    <xacro:property name="num_elements" value="1" />

    <xacro:property name="elem_length_main" value="${tether_length/num_elements}" />
    <!-- <xacro:property name="elem_length_ends" value="0.01" /> -->
    <xacro:property name="elem_mass_main" value="${tether_mass/num_elements}" />
    <!-- <xacro:property name="elem_mass_ends" value="${elem_mass_main*(elem_length_ends/elem_length_main)}" /> -->

    <!-- Define link macro -->
    <xacro:macro name="tether_element" params="element_num elem_length elem_mass">
        <link name="element_${element_num}">
            <inertial>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <mass value="${elem_mass}"/>
                <inertia ixx="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" ixy="0" ixz="0" iyy="${1/12*elem_mass*(3*tether_radius**2 + elem_length**2)}" iyz="0" izz="${1/2*elem_mass*(tether_radius**2)}" />
            </inertial>
            <visual>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <cylinder length="${elem_length}" radius="${tether_radius}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="${elem_length/2} 0 0" rpy="0 ${pi/2} 0" />
                <geometry>
                    <!-- <cylinder length="${elem_length}" radius="${tether_radius}"/> -->
                    <cylinder length="0.0001" radius="0.0001"/>
                </geometry>
                <!-- <surface>
                    <contact>
                        <collide_without_contact>true</collide_without_contact>
                    </contact>
                </surface> -->
            </collision>
        </link>
    </xacro:macro>


    <!-- Recursive loop to generate multiple elements and joints for said elements -->
    <xacro:macro name="generate_tether" params="elem_num">
        <!-- Generate elements and recurse-->
        <xacro:tether_element element_num="${elem_num}" elem_length="${elem_length_main}" elem_mass="${elem_mass_main}" />

        <xacro:if value="${elem_num-1}">
            <xacro:generate_tether elem_num="${elem_num-1}" />
        </xacro:if>

        <!-- Define joints -->
        <xacro:if value="${elem_num-1 > 0}">
            <joint name="joint_${elem_num-1}_to_${elem_num}" type="continuous">
                <axis xyz="0. 1. 1."/>
                <origin xyz="${elem_length_main} 0 0" rpy="0 0 0"/>
                <parent link="element_${elem_num-1}"/>
                <child link="element_${elem_num}"/>

                <dynamics damping="10.0" friction="0.0"/>
            </joint>

        </xacro:if>

    </xacro:macro>

    <!-- Call recursive loop to generate tether -->
    <xacro:generate_tether elem_num="${num_elements}" />

    <!-- Add start and end elements and joints-->
    <!-- <xacro:tether_element element_num="0" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" />
    <xacro:tether_element element_num="${num_elements+1}" elem_length="${elem_length_ends}" elem_mass="${elem_mass_ends}" /> -->

    <!-- <joint name="joint_0_to_1" type="continuous">
        <axis xyz="0. 1. 1."/>
        <origin xyz="${elem_length_ends} 0 0" rpy="0 0 0"/>
        <parent link="element_0"/>
        <child link="element_1"/>
    </joint>
    <joint name="joint_${num_elements}_to_${num_elements+1}" type="continuous">
        <axis xyz="0. 1. 1."/>
        <origin xyz="${elem_length_main} 0 0" rpy="0 0 0"/>
        <parent link="element_${num_elements}"/>
        <child link="element_${num_elements+1}"/>
    </joint> -->




    <!-- Define joints -->
        <!-- Add start element joint-->
        <!-- <xacro:if value="${elem_num-1 == 0}">
            <joint name="joint_${elem_num-1}_to_${elem_num}" type="fixed">
                <axis xyz="0. 0. 1."/>
                <origin xyz="${elem_length} 0 0" rpy="0 0 0"/>
                <parent link="element_${elem_num-1}"/>
                <child link="element_${elem_num}"/>
            </joint>
        </xacro:if> -->

</robot>
